version: '3'

services:
  minio:
    image: bitnami/minio:2022
    networks: ['ticketer']
    volumes: ['minio_data:/data']
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_SERVER_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SERVER_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_DEFAULT_BUCKETS=ticketer
      - MINIO_SERVER_HOST=${MINIO_SERVER_HOST}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    restart: unless-stopped
  mariadb:
    image: mariadb:10.6
    networks: ['ticketer']
    volumes: ['mariadb_data:/var/lib/mysql']
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=ticketer
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
  redis:
    image: redis:7.2.5-alpine
    networks: ["ticketer"]
    restart: unless-stopped
  ticketer:
    build: .
    pull_policy: build
    networks: ['ticketer']
    volumes: ['ticketer_data:/ticketer/data']
    environment:
      - DB_CONNECTION_STRING=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mariadb/ticketer
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - JWT_KEY=${JWT_KEY}
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - S3_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - PAYPAL_ID=${PAYPAL_ID}
      - PAYPAL_SECRET=${PAYPAL_SECRET}
      - REDIS_URL=redis://redis
      - RECAPTCHA_SITEKEY=${RECAPTCHA_SITEKEY}
      - RECAPTCHA_SECRET=${RECAPTCHA_SECRET}
    depends_on:
      - minio
      - mariadb
    restart: unless-stopped
  nginx:
    image: nginx
    pull_policy: build
    ports:
      - '127.0.0.1:8000:80'
    networks: ['ticketer']
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on: [ticketer]
    restart: unless-stopped

networks:
  ticketer:
    driver: bridge

volumes:
  minio_data:
    driver: local
  mariadb_data:
    driver: local
  ticketer_data:
    driver: local